# Generated by Django 6.0.3 on 2026-05-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_organization_alter_candidate_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('email', 'organization')},
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новий'), ('screening', 'Скринінг'), ('interview', 'Співбесіда'), ('offer', 'Оффер'), ('rejected', 'Відмова')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'Новий'), ('screening', 'Скринінг'), ('interview', 'Співбесіда'), ('offer', 'Оффер'), ('rejected', 'Відмова')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='candidates.candidate')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Історія статусу',
                'verbose_name_plural': 'Історія статусів',
                'db_table': 'candidate_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
