# Generated by Django 6.0.3 on 2026-05-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_statushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('interview', "Запрошення на інтерв'ю"), ('rejection', 'Відмова'), ('offer', 'Оффер')], max_length=20)),
                ('subject', models.CharField(default='', max_length=300)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='candidates.organization')),
            ],
            options={
                'ordering': ['template_type'],
                'unique_together': {('organization', 'template_type')},
            },
        ),
    ]
