# Generated by Django 6.0.3 on 2026-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('dou', 'DOU'), ('recommendation', 'Рекомендація'), ('csv', 'CSV'), ('direct', 'Прямий відгук'), ('other', 'Інше')], default='other', max_length=20),
        ),
    ]
