# Generated by Django 6.0.3 on 2026-05-21 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_tag_candidate_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], default='online', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Заплановано'), ('completed', 'Проведено'), ('cancelled', 'Скасовано'), ('rescheduled', 'Перенесено')], default='scheduled', max_length=15)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('google_meet_link', models.URLField(blank=True)),
                ('google_calendar_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interviews_as_interviewer', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.organization')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='candidates.vacancy')),
            ],
            options={
                'verbose_name': "Інтерв'ю",
                'verbose_name_plural': "Інтерв'ю",
                'ordering': ['scheduled_at'],
            },
        ),
    ]
