# Generated by Django 6.0.3 on 2026-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис вакансії'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='dou_vacancy_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Повна зайнятість'), ('part_time', 'Часткова зайнятість'), ('volunteer', 'Волонтерство'), ('contract', 'Контракт')], default='volunteer', max_length=20, verbose_name='Тип зайнятості'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='linkedin_vacancy_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at_dou',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at_linkedin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at_rabota_ua',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at_work_ua',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_dou',
            field=models.BooleanField(default=False, verbose_name='DOU'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_linkedin',
            field=models.BooleanField(default=False, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_rabota_ua',
            field=models.BooleanField(default=False, verbose_name='rabota.ua'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_work_ua',
            field=models.BooleanField(default=False, verbose_name='work.ua'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='rabota_ua_vacancy_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Вимоги'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата від'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_ua_vacancy_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('dou', 'DOU'), ('work_ua', 'work.ua'), ('rabota_ua', 'rabota.ua'), ('recommendation', 'Рекомендація'), ('csv', 'CSV'), ('direct', 'Прямий відгук'), ('other', 'Інше')], default='other', max_length=20),
        ),
    ]
