# Generated by Django 6.0.3 on 2026-05-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_vacancy_city_vacancy_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва шаблону')),
                ('category', models.CharField(choices=[('it', 'IT'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('hr', 'HR'), ('finance', 'Finance'), ('operations', 'Operations'), ('design', 'Design'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Категорія')),
                ('title', models.CharField(max_length=200, verbose_name='Назва вакансії')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Відділ')),
                ('description', models.TextField(blank=True, verbose_name='Опис вакансії')),
                ('requirements', models.TextField(blank=True, verbose_name='Вимоги')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Повна зайнятість'), ('part_time', 'Часткова зайнятість'), ('volunteer', 'Волонтерство'), ('contract', 'Контракт')], default='volunteer', max_length=20, verbose_name='Тип зайнятості')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_templates', to='candidates.organization')),
            ],
            options={
                'verbose_name': 'Шаблон вакансії',
                'verbose_name_plural': 'Шаблони вакансій',
                'ordering': ['category', 'name'],
            },
        ),
    ]
