# Generated by Django 6.0.3 on 2026-05-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_vacancytemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва організації')),
                ('reason', models.TextField(blank=True, verbose_name='Причина блокування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_orgs', to=settings.AUTH_USER_MODEL, verbose_name='Додав')),
            ],
            options={
                'verbose_name': 'Заблокована організація',
                'verbose_name_plural': 'Чорний список організацій',
                'ordering': ['-created_at'],
            },
        ),
    ]
