# Generated by Django 6.0.3 on 2026-05-30 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_blacklistedorganization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedorganization',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заблокована організація', 'verbose_name_plural': 'Заблоковані організації'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.AlterField(
            model_name='blacklistedorganization',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blacklistedorganization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blacklistedorganization',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='category',
            field=models.CharField(choices=[('it', 'IT'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('hr', 'HR'), ('finance', 'Finance'), ('operations', 'Operations'), ('design', 'Design'), ('other', 'Інше')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Повна зайнятість'), ('part_time', 'Часткова зайнятість'), ('volunteer', 'Волонтерство'), ('contract', 'Контракт')], default='volunteer', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='VacancyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#7a1a2e', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('system_key', models.CharField(blank=True, choices=[('new', 'Новий'), ('screening', 'Скринінг'), ('interview', 'Співбесіда'), ('offer', 'Оффер'), ('rejected', 'Відмова')], db_index=True, max_length=20, null=True)),
                ('is_terminal', models.BooleanField(default=False, help_text='Фінальний етап (Відмова, Найнятий тощо)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='candidates.organization')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='candidates.vacancy')),
            ],
            options={
                'verbose_name': 'Етап вакансії',
                'verbose_name_plural': 'Етапи вакансій',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='candidates.vacancystage', verbose_name='Етап'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='new_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='candidates.vacancystage'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='old_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='candidates.vacancystage'),
        ),
    ]
