# Generated by Django 6.0.3 on 2026-05-31 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_alter_blacklistedorganization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_type', models.CharField(choices=[('new_year', 'Новорічний'), ('halloween', 'Хеллоуїн'), ('independence', 'День Незалежності'), ('ida_birthday', 'День народження ІДА'), ('default', 'Звичайний')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('css_variables', models.JSONField(default=dict)),
                ('hero_image', models.URLField(blank=True)),
                ('background_image', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#7a1a2e', max_length=7)),
                ('secondary_color', models.CharField(default='#4a0f1c', max_length=7)),
                ('accent_color', models.CharField(default='#e8a0b0', max_length=7)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тематичне оформлення',
                'verbose_name_plural': 'Тематичні оформлення',
                'ordering': ['theme_type'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('discount_valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_hr', models.IntegerField(default=3)),
                ('max_vacancies', models.IntegerField(default=10)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_email_templates', models.BooleanField(default=False)),
                ('has_google_integration', models.BooleanField(default=False)),
                ('has_custom_stages', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Конфігурація цін',
                'verbose_name_plural': 'Конфігурації цін',
            },
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['scheduled_at']},
        ),
        migrations.AlterModelOptions(
            name='sentemail',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='vacancystage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='blacklistedorganization',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklistedorganization',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='candidates.vacancystage'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Повна зайнятість'), ('part_time', 'Часткова зайнятість'), ('volunteer', 'Волонтерство'), ('contract', 'Контракт')], default='volunteer', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_dou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_rabota_ua',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_work_ua',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancytemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток'), ('fixed', 'Фіксована сума')], default='percent', max_length=10)),
                ('discount_value', models.PositiveIntegerField()),
                ('applicable_plans', models.JSONField(blank=True, default=list)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Промо-код',
                'verbose_name_plural': 'Промо-коди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_to_plan', models.CharField(max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.organization')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='candidates.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Використання промо-коду',
                'verbose_name_plural': 'Використання промо-кодів',
                'ordering': ['-used_at'],
            },
        ),
    ]
