# Generated by Django 6.0.3 on 2026-06-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_holidaytheme_pricingconfig_alter_interview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='rejection_comment',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reasons', to='candidates.organization')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='statushistory',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='candidates.rejectionreason'),
        ),
    ]
