# Generated by Django 6.0.3 on 2026-06-03 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_statushistory_rejection_comment_rejectionreason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний HR'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Перегляд'), ('create', 'Створення'), ('update', 'Оновлення'), ('delete', 'Видалення'), ('status_change', 'Зміна статусу'), ('assign', 'Призначення'), ('export', 'Експорт'), ('access_grant', 'Надання доступу'), ('access_revoke', 'Відкликання доступу')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='candidates.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог дій',
                'verbose_name_plural': 'Логи дій',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='candidates__user_id_676894_idx'), models.Index(fields=['model_name', 'object_id'], name='candidates__model_n_0f24a6_idx'), models.Index(fields=['organization', 'created_at'], name='candidates__organiz_422b81_idx')],
            },
        ),
        migrations.CreateModel(
            name='VacancyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_access', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_access', to='candidates.vacancy')),
            ],
            options={
                'verbose_name': 'Доступ до вакансії',
                'verbose_name_plural': 'Делеговані доступи',
                'unique_together': {('vacancy', 'user')},
            },
        ),
    ]
