# Generated by Django 6.0.3 on 2026-06-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_externalapikey_webhookendpoint_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gdpr_anonymized',
            field=models.BooleanField(default=False, help_text='Персональні дані анонімізовані'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gdpr_anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gdpr_consent',
            field=models.BooleanField(default=False, help_text='Кандидат надав згоду на обробку персональних даних'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gdpr_consent_date',
            field=models.DateTimeField(blank=True, help_text='Дата надання згоди', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gdpr_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP-адреса при наданні згоди', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gdpr_consent_text',
            field=models.TextField(blank=True, help_text='Текст згоди на момент підписання'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gdpr_delete_after',
            field=models.DateField(blank=True, help_text='Дата автовидалення (розраховується з consent_date + retention period)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gdpr_withdraw_date',
            field=models.DateTimeField(blank=True, help_text='Дата відкликання згоди', null=True),
        ),
        migrations.CreateModel(
            name='GDPRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Скільки днів зберігати дані кандидата після надання згоди')),
                ('consent_text', models.TextField(default='Я надаю згоду на обробку моїх персональних даних відповідно до Регламенту ЄС 2016/679 (GDPR) та законодавства України. Мої дані використовуватимуться виключно з метою розгляду моєї кандидатури на відкриті вакансії. Я маю право відкликати цю згоду в будь-який час, звернувшись до відповідального за обробку даних.', help_text='Текст згоди, який показується кандидатам')),
                ('auto_anonymize', models.BooleanField(default=True, help_text='Автоматично анонімізувати кандидатів після закінчення терміну зберігання')),
                ('notify_before_days', models.PositiveIntegerField(default=30, help_text='За скільки днів до видалення надсилати сповіщення адміну')),
                ('dpo_email', models.EmailField(blank=True, help_text='Email відповідального за захист даних (DPO)', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_settings', to='candidates.organization')),
            ],
            options={
                'verbose_name': 'GDPR налаштування',
                'verbose_name_plural': 'GDPR налаштування',
            },
        ),
    ]
