# Generated by Django 6.0.3 on 2026-06-10 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidate_gdpr_anonymized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Умова завдання (Markdown підтримується)')),
                ('task_type', models.CharField(choices=[('code', 'Код (авто-перевірка)'), ('text', 'Текстова відповідь'), ('quiz', 'Тест з варіантами'), ('file', 'Завантаження файлу'), ('link', 'Посилання (GitHub, Figma, тощо)')], default='text', max_length=20)),
                ('language', models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('go', 'Go'), ('rust', 'Rust'), ('sql', 'SQL'), ('other', 'Інше')], max_length=20)),
                ('starter_code', models.TextField(blank=True, help_text='Початковий шаблон коду')),
                ('solution_code', models.TextField(blank=True, help_text="Еталонний розв'язок (не показується кандидату)")),
                ('test_cases', models.JSONField(default=list, help_text='[{"input": "...", "expected_output": "...", "is_hidden": false}]')),
                ('time_limit_sec', models.PositiveIntegerField(default=10, help_text='Ліміт часу виконання (секунд)')),
                ('memory_limit_mb', models.PositiveIntegerField(default=128, help_text="Ліміт пам'яті (МБ)")),
                ('quiz_options', models.JSONField(default=list, help_text='[{"text": "Варіант A", "is_correct": true}, ...]')),
                ('time_limit_minutes', models.PositiveIntegerField(default=60, help_text='Максимальний час на виконання завдання кандидатом (хвилини)')),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='candidates.organization')),
                ('vacancy', models.ForeignKey(blank=True, help_text='Якщо вказано — завдання показується тільки для цієї вакансії', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='candidates.vacancy')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує виконання'), ('sent', 'Надіслано кандидату'), ('in_progress', 'Виконується'), ('submitted', 'Здано на перевірку'), ('checking', 'Перевіряється'), ('passed', 'Пройдено'), ('failed', 'Не пройдено'), ('expired', 'Час вийшов')], default='pending', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('hr_comment', models.TextField(blank=True, help_text='Коментар HR після перевірки')),
                ('auto_result', models.JSONField(blank=True, help_text='Результат авто-перевірки коду: {passed, failed, errors, execution_time}', null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='candidates.candidate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='candidates.task')),
            ],
            options={
                'verbose_name': 'Видача завдання',
                'verbose_name_plural': 'Видачі завдань',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('code_answer', models.TextField(blank=True)),
                ('selected_options', models.JSONField(default=list)),
                ('file_url', models.URLField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('run_result', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='candidates.taskassignment')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
            },
        ),
    ]
