# Generated by Django 6.0.3 on 2026-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_task_taskassignment_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='di_age_range',
            field=models.CharField(blank=True, choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55+', '55+'), ('prefer_not', 'Не вказувати')], max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='di_consent',
            field=models.BooleanField(default=False, help_text='Окрема згода на збір D&I даних (GDPR)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='di_disability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='di_gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('non_binary', 'Небінарний/а'), ('prefer_not', 'Не хочу вказувати'), ('other', 'Інше')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='di_veteran',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
