# Generated by Django 6.0.3 on 2026-06-19 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidate_di_age_range_candidate_di_consent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Кандидат заблокований модератором'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Вакансія заблокована модератором'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'Перегляд'), ('create', 'Створення'), ('update', 'Оновлення'), ('delete', 'Видалення'), ('status_change', 'Зміна статусу'), ('assign', 'Призначення'), ('export', 'Експорт'), ('access_grant', 'Надання доступу'), ('access_revoke', 'Відкликання доступу'), ('block', 'Блокування'), ('unblock', 'Розблокування')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Супер-адмін'), ('admin', 'Адмін організації'), ('hr', 'HR менеджер'), ('moderator', 'Модератор')], default='hr', max_length=20),
        ),
        migrations.CreateModel(
            name='ModeratorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_notes', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notes', to='candidates.candidate')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notes', to='candidates.vacancy')),
            ],
            options={
                'verbose_name': 'Нотатка модератора',
                'verbose_name_plural': 'Нотатки модераторів',
                'ordering': ['-created_at'],
            },
        ),
    ]
