# Generated by Django 6.0.3 on 2026-06-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_candidate_block_reason_candidate_blocked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(blank=True, help_text='PDF, DOC або DOCX (макс. 10 МБ)', null=True, upload_to='cvs/%Y/%m/', verbose_name='CV файл'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригінальна назва файлу CV'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завантаження CV'),
        ),
    ]
