# Generated by Django 6.0.3 on 2026-06-24 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0023_candidate_cv_file_candidate_cv_original_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta_open', models.BooleanField(default=True, help_text='Якщо вимкнено — форма на лендінгу показує «реєстрацію закрито»', verbose_name='Реєстрацію відкрито')),
                ('max_slots', models.PositiveIntegerField(default=20, verbose_name='Максимум учасників')),
                ('notify_email', models.EmailField(blank=True, help_text='Куди надсилати сповіщення про нові заявки', max_length=254, verbose_name='Email для сповіщень')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування бети',
                'verbose_name_plural': 'Налаштування бети',
            },
        ),
        migrations.CreateModel(
            name='BetaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Агенція')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Контактна особа')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('team_size', models.CharField(blank=True, choices=[('1-2', '1–2 людини'), ('3-5', '3–5 людей'), ('6-10', '6–10 людей'), ('11+', '11+ людей')], max_length=20, verbose_name='Розмір команди')),
                ('current_tool', models.CharField(blank=True, choices=[('google_sheets', 'Google Sheets / Excel'), ('notion', 'Notion / Airtable'), ('trello', 'Trello / Jira'), ('ats', 'Інша ATS'), ('nothing', 'Нічого системного')], max_length=50, verbose_name='Поточний інструмент')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('pending', 'Нова заявка'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, verbose_name='Нотатка адміна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False, verbose_name='Лист відправлено')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_beta_apps', to=settings.AUTH_USER_MODEL, verbose_name='Переглянув')),
            ],
            options={
                'verbose_name': 'Заявка на бету',
                'verbose_name_plural': 'Заявки на бету',
                'ordering': ['-created_at'],
            },
        ),
    ]
